### ISSUE TITLE
Object Array deep copy

### ISSUE THREAD

**Issue by pavou** [mvrozanti/octree#1]
> is this an accurate translation for that condition? 

Given each Point will be a java object either you make the object imutable by design (private setters) 
or 
you must iterate the array and call clone (give it's implemented) on each point to create new points and add them to the new array. 

Otherwise the points will still reference the same memory

**Comment by mvrozanti** [comment]
Thank you for giving that C++ insight. I don't really see a problem with this in Java though. The objects aren't modified, even in J. Behley's implementation so I think just wrapping the list when the flag is enabled should be good, do you agree?
